version: '3.7'

services:
  db:
    image: postgres
    restart: always
    container_name: book_db
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=secret
       - POSTGRES_DB=book-db
    ports:
        - '5432:5432'